### ISSUE TITLE
Fix implementation for api request / endpoint for use case 1 (isActive checker)

### ISSUE THREAD

**Issue by michaelwoodruffdev** [michaelwoodruffdev/augur#2]
Most of our efforts so far have been to learn and understand how the vue framework works and how it is implemented in the Augur front-end. 

For sprint 3, we also need to gain an understanding of the backend api created with Flask and other technologies.

What we know:
    1. The current repo being observed is stored in the Vuex store as a field called 'gitRepo'. 
        For our implementation we will only focus on this one, and possibly expand it to be useful 
        in comparing the repos stored in the vuex stores 'comparedRepos' array. 
    2. There are already endpoints created that might be of use within the Flask API. 
    3. If we need to create our own endpoint, we can do so within the different Flask plugins 
        associated with the data sources we need. 

Steps:
    1. Find out if we can use a preexisting api endpoint, if we can, use it for use case 1
    2. If no endpoint found, implement our own withing the Flask Plugin for the 
        GHTorrent data source. 

Note: 
    if we can use a preexisting api endpoint, use case 1 will likely be pretty easy to implement. 
    if this is the case, we should do the same for many of the 'filters' for use case 2 while still 
    in the sprint 3 timeframe.

**Comment by JordanWieberg** [comment]
Right now we're just trying to successfully make a request to the AugurAPI to find the number of commits on the base repo in the last 30 days. Right now we're experimenting with commits100 in GHTorrent.

fetch(`/${apiPlug}/timeseries/commits100`)
      .then(response => {
        this.log = response.json();
        window.alert("got a response");
        console.log(response.json());
      })
      .catch(err => {
        window.alert(err);
      });

We are receiving a response, but we are not receiving any data from the API.

**Comment by michaelwoodruffdev** [comment]
Commits100 looks like it doesn't actually do anything that would help us. We are going to try and use the commits by week endpoint. this uses the facade datasource, which requires a base64 encoded git repo name. We are looking at standard web api's to convert our git repo string to base64 so we can use this endpoint

**Comment by michaelwoodruffdev** [comment]
After meeting with goggins, we re-implemented the commits100 function in the backend, so that it returns a true or false value depending on if there has been a commit in the past 210 days. This will be used to determine if we should display 'active' or 'inactive' on our component. We use 210 days rather than 30 days because we are using an outdated data set in ghtorrent, therefore for testing, we go back to 210 days.

**Comment by michaelwoodruffdev** [comment]
I'm having issues with making the api request. I am currently getting back a response object with no body but a status of 200. I am going to go into office hours to figure it out. I'm sure I'm just missing something simple with the fetch API.
Here is the updated backend code for our commits100 function... 

`@annotate(tag='commits100')
    def commits100(self, owner, repo=None):

        repoid = self.repoid(owner, repo)
        commitsSQL = s.sql.text("""
            SELECT COUNT(*) AS 'commits_count'
            FROM commits
            WHERE commits.project_id = :repoid
            AND
            created_at > (CURRENT_DATE-220) 
        """)

        temp = pd.read_sql(commitsSQL, self.db, params={"repoid": str(repoid)})
        tem = temp['commits_count'] > 0
        return tem
`

**Comment by michaelwoodruffdev** [comment]
edited the backend commits100 function to try to get this to work
`@annotate(tag='commits100')
    def commits100(self, owner, repo=None):

        repoid = self.repoid(owner, repo)
        commitsSQL = s.sql.text("""
            SELECT COUNT(*) AS 'commits_count'
            FROM commits
            WHERE commits.project_id = :repoid
            AND
            created_at > (CURRENT_DATE-220) 
        """)

        temp = pd.read_sql(commitsSQL, self.db, params={"repoid": str(repoid)})
        logger.info(temp)
        tem = temp['commits_count'] > 0
        logger.info(tem)
        return json.dumps(temp.to_dict())
`
